import sys, os
import matplotlib.pyplot as plt
import numpy as np

filePath_gt = '../../../../data/6-DOF-Objects/synthetic/006mustard/'

gt_trans_x = np.genfromtxt(os.path.join(filePath_gt, 'translation_x_gt_velocity_1m_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])
gt_trans_y = np.genfromtxt(os.path.join(filePath_gt, 'translation_y_gt_velocity_1m_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])
gt_trans_z = np.genfromtxt(os.path.join(filePath_gt, 'translation_z_gt_velocity_1m_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])
gt_roll = np.genfromtxt(os.path.join(filePath_gt, 'roll_gt_velocity_2rad_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])
gt_pitch = np.genfromtxt(os.path.join(filePath_gt, 'pitch_gt_velocity_2rad_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])
gt_yaw = np.genfromtxt(os.path.join(filePath_gt, 'yaw_gt_velocity_2rad_s/ground_truth.csv'), delimiter=",", names=["t", "x", "y", "z", "qx", "qy", "qz", "qw"])

fig1, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_trans_x['t'], gt_trans_x['x'], 'r--', label='x gt')
ax1.plot(gt_trans_x['t'], gt_trans_x['y'], 'g--', label='y gt')
ax1.plot(gt_trans_x['t'], gt_trans_x['z'], 'b--', label='z gt')
ax2.plot(gt_trans_x['t'], gt_trans_x['qx'], 'k--', label='qx gt')
ax2.plot(gt_trans_x['t'], gt_trans_x['qy'], 'y--', label='qy gt')
ax2.plot(gt_trans_x['t'], gt_trans_x['qz'], 'm--', label='qz gt')
ax2.plot(gt_trans_x['t'], gt_trans_x['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Translation along x of mustard bottle')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()

fig2, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_trans_y['t'], gt_trans_y['x'], 'r--', label='x gt')
ax1.plot(gt_trans_y['t'], gt_trans_y['y'], 'g--', label='y gt')
ax1.plot(gt_trans_y['t'], gt_trans_y['z'], 'b--', label='z gt')
ax2.plot(gt_trans_y['t'], gt_trans_y['qx'], 'k--', label='qx gt')
ax2.plot(gt_trans_y['t'], gt_trans_y['qy'], 'y--', label='qy gt')
ax2.plot(gt_trans_y['t'], gt_trans_y['qz'], 'm--', label='qz gt')
ax2.plot(gt_trans_y['t'], gt_trans_y['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Translation along y of mustard bottle')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()

fig3, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_trans_z['t'], gt_trans_z['x'], 'r--', label='x gt')
ax1.plot(gt_trans_z['t'], gt_trans_z['y'], 'g--', label='y gt')
ax1.plot(gt_trans_z['t'], gt_trans_z['z'], 'b--', label='z gt')
ax2.plot(gt_trans_z['t'], gt_trans_z['qx'], 'k--', label='qx gt')
ax2.plot(gt_trans_z['t'], gt_trans_z['qy'], 'y--', label='qy gt')
ax2.plot(gt_trans_z['t'], gt_trans_z['qz'], 'm--', label='qz gt')
ax2.plot(gt_trans_z['t'], gt_trans_z['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Translation along x of mustard bottle')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()

fig4, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_roll['t'], gt_roll['x'], 'r--', label='x gt')
ax1.plot(gt_roll['t'], gt_roll['y'], 'g--', label='y gt')
ax1.plot(gt_roll['t'], gt_roll['z'], 'b--', label='z gt')
ax2.plot(gt_roll['t'], gt_roll['qx'], 'k--', label='qx gt')
ax2.plot(gt_roll['t'], gt_roll['qy'], 'y--', label='qy gt')
ax2.plot(gt_roll['t'], gt_roll['qz'], 'm--', label='qz gt')
ax2.plot(gt_roll['t'], gt_roll['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Rotation around object x-axis')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()

fig5, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_pitch['t'], gt_pitch['x'], 'r--', label='x gt')
ax1.plot(gt_pitch['t'], gt_pitch['y'], 'g--', label='y gt')
ax1.plot(gt_pitch['t'], gt_pitch['z'], 'b--', label='z gt')
ax2.plot(gt_pitch['t'], gt_pitch['qx'], 'k--', label='qx gt')
ax2.plot(gt_pitch['t'], gt_pitch['qy'], 'y--', label='qy gt')
ax2.plot(gt_pitch['t'], gt_pitch['qz'], 'm--', label='qz gt')
ax2.plot(gt_pitch['t'], gt_pitch['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Rotation around object y-axis')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()

fig6, (ax1, ax2) = plt.subplots(2)
ax1.plot(gt_yaw['t'], gt_yaw['x'], 'r--', label='x gt')
ax1.plot(gt_yaw['t'], gt_yaw['y'], 'g--', label='y gt')
ax1.plot(gt_yaw['t'], gt_yaw['z'], 'b--', label='z gt')
ax2.plot(gt_yaw['t'], gt_yaw['qx'], 'k--', label='qx gt')
ax2.plot(gt_yaw['t'], gt_yaw['qy'], 'y--', label='qy gt')
ax2.plot(gt_yaw['t'], gt_yaw['qz'], 'm--', label='qz gt')
ax2.plot(gt_yaw['t'], gt_yaw['qw'], 'c--', label='qw gt')
ax1.legend()
ax2.legend()
plt.suptitle('Rotation around object z-axis')
ax1.set(ylabel='Position[m]')
ax2.set(xlabel='Time [s]', ylabel='Quaternions')
plt.show()
